version: '{build}'
init:
- cmd: >-
    choco install dotnetcore --version 1.0.0.001598 --yes

    set path=%path%;C:\Program Files\dotnet\bin
install:
- cmd: dotnet restore
cache: C:\Users\appveyor\.nuget\packages
build_script:
- ps: >-
    dotnet build nautilus --configuration Release

    nuget install LibZ.Tool -Version 1.2.0

    ".\LibZ.Tool.1.2.0.0\tools\libz.exe" inject-dll --assembly ".\nautilus\bin\Release\dnx451\win7-x64\nautilus.exe" --include ".\nautilus\bin\Release\dnx451\win7-x64\*.dll" --move

    Get-ChildItem .\nautilus\bin\Release\dnx451\win7-x64\nautilus.exe | % { Push-AppveyorArtifact $_.FullName }

    nuget pack Nautilus.nuspec -NoPackageAnalysis

    Get-ChildItem .\Nautilus.*.nupkg | % { Push-AppveyorArtifact $_.FullName -DeploymentName Chocolatey }

    $rnp = Resolve-Path(".\RELEASENOTES.md")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_notes -Value $rnc
deploy:
- provider: GitHub
  description: $(release_notes)
  auth_token:
    secure: ajroRFK4yrBdtuy7wNRKY5evo9TCGzz0wRzeemVUMHYXQ61AU/6c37A+3hZw/vc2
  prerelease: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: wCneazo7/uf7Y9f4rDIFQ8z33kEWQGS/gcxPhQlB1X7mudqlLTGp5xeWCly3zZ4G
  artifact: Chocolatey
  on:
    appveyor_repo_tag: true